
all: lab_12

lab12test: item.o
	g++ -Wall -g -o item item.o

lab_12: item.cpp
	g++ -Wall -g -c item.cpp
	
lab_12: food_item.cpp
	g++ -Wall -g -c food_item.cpp
	
lab_12: magic_item.cpp
	g++ -Wall -g -c magic_item.cpp

lab_12: lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp
	